config/routes.rb
Rails.application.routes.draw do

  get 'advance/index'

  get 'intermediated/index'

  get 'school/index'

  get 'dashboard/index'

  root 'user#index'
  resource :user
  resource :dashboard

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/business.rb
class Business < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/advance_controller.rb
class AdvanceController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/intermediated_controller.rb
class IntermediatedController < ApplicationController
  def index
  end
end

app/controllers/school_controller.rb
class SchoolController < ApplicationController
  def index
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end
end

app/helpers/advance_helper.rb
module AdvanceHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/intermediated_helper.rb
module IntermediatedHelper
end

app/helpers/school_helper.rb
module SchoolHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/advance/index.html.erb
<div class="container">
  <h3 class="header text-muted text-center">
    <strong><i class="fa fa-github" aria-hidden="true"></i> API, Ruby on Rails, AngularJs SPA...... </strong>
  </h3>

  <div class="container">
    <h4 class="header">
      <strong class="text-info"><i class="fa fa-hand-o-right" aria-hidden="true"></i>Angular on Rails JSON API...TODO
        APPLICATION</strong>
      <%= link_to '<strong>Github</strong><i class="fa fa-github"></i>'.html_safe, 'https://github.com/surajneupane55/Rails-API-on-Angularjs', class: 'btn btn-success', class: 'btn btn-success pull-right', :target => '_blank' %>

      <%= link_to  '<strong>Demo app</strike></strong><i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i>'.html_safe, 'https://radiant-coast-44956.herokuapp.com/', class: 'btn btn-success pull-right', :target => '_blank' %>


    </h4>

    <div class="row placeholders">
      <div class="col-md-6">
        <%= image_tag('api-img2.png', :alt => ' Generic placeholder thumbnail', class: 'img-rounded') %>

      </div>
      <div class="col-md-6">
        <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading "><strong>API test with curl</strong></div>
          <div class="panel-body">
            <p>Providing basic http authentication USERNAME:PASSWORD create a session in API and should return a
              authenticate_token:
              <code> https://radiant-coast-44956.herokuapp.com/api/session -d '' -u abc@123.com:12345678</code></p>
          </div>

          <!-- List group -->
          <ul class="list-group">
            <li class="list-group-item">Return back TOKEN is build inside request header for further CURD communication
              with API.
              <code>@host = curl -H "X-Authenticate-Token: TOKEN" https://radiant-coast-44956.herokuapp.com/</code></li>
            <li class="list-group-item">Lists all the Task for authenticated user: <code>@host/api/tasks.json</code>
            </li>
            <li class="list-group-item">Lists all todo for task : <code>@host/api/tasks/task_id/lists.json</code>
            </li>
            <li class="list-group-item">Create new task with :task_id :
              <code>@host/api/tasks -d '{"task": {"name": "Mother's Day todo"}}' -H 'Content-Type:
                application/json'</code></li>
            <li class="list-group-item">Update task with task_id :
              <code>@host/api/tasks/task_id -d '{"task": {"name": "Mother's Day morning todo"}}' -H 'Content-Type:
                application/json' -X PATCH
              </code></li>
            <li class="list-group-item">Lists all todo list for Task with task_id :
              <code>@host/api/tasks/task_id/lists</code></li>
            <li class="list-group-item">Create todo list item for Task with task_id :
              <code>@host/api/tasks/task_id/lists -d '{"list": {"description": "travelling"}}' -H 'Content-Type:
                application/json'</code></li>
            <li class="list-group-item">Update todo list item for task with task_id :
              <code>@host/api/tasks/task_id/list/list_id -d '{"list": {"due_date": "2016-05-04"}}' -H 'Content-Type:
                application/json' -X PATCH</code></li>
            <li class="list-group-item"><strong>Delete session for active user</strong>
              <code>https://radiant-coast-44956.herokuapp.com/api/session?authenticate_token=TOKEN -X DELETE</code></li>

          </ul>
        </div>
          <div class="text-center">
            <%= link_to dashboard_index_path, class: 'btn btn-info' do %>
                <i class="fa fa-arrow-left" aria-hidden="true"></i><strong> Back to Dashboard </strong>
            <% end %>
          </div>
      </div>
    </div>
  </div>
  <br>

  <!--  <h4 class="header">
      <strong><i class="fa fa-hand-o-right" aria-hidden="true"></i> PHP learning stock trading...</strong>
    </h4>

    <p>
    <h4>
      <small>
        <strike>Create secure account where 10000 USD will be deposited and choose a NASDAQ stocks to buy or sales and
          track your performances. No real money is involved just for learning purpose</strike></small>
      <h4 class="text-danger"><strong> Work in progress.....</strong></h4>
    </h4>
    </p>
    <div class="row placeholders">
      <div class="col-md-6">
      </div>
    </div>-->


</div>

app/views/application/_footer.html.erb
<div class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    <p class="text-center"><span class="glyphicon glyphicon-copyright-mark"></span> SURAJ NEUPANE 2016</p>
  </div>
</div>

app/views/application/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button>
              </div>
              <div class="navbar-collapse collapse">
                  <ul class="nav navbar-nav navbar-right">
                      <li><%=link_to '<i class="fa fa-male"></i> Profile'.html_safe,root_path %></li>
                  </ul>
              </div>
      </div>
    </div>

app/views/dashboard/index.html.erb
<div class="container">
  <h3 class=" header text-muted text-center">
    <i class="fa fa-signal"></i>
    <strong>Dashboard</strong>
  </h3>

  <div class="container">
    <div class="row placeholders">
      <div class="col-md-4 placeholder text-center">
        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal">
          <strong>Basic School
            Projects </strong><i class="fa fa-bars"></i><i class="fa fa-arrow-circle-o-down"></i>
        </button>
      </div>
      <div class=" col-md-4 placeholder text-center">
        <%= link_to intermediated_index_path, class: 'btn btn-success' do %>
            <strong>Intermediate
              Projects </strong><i class="fa fa-bars"></i><i class="fa fa-arrow-circle-o-down"></i>
        <% end %>
      </div>
      <div class="col-md-4 placeholder text-center">
        <%= link_to advance_index_path, class: 'btn btn-success' do %>
            <strong>Advance
              Projects </strong><i class="fa fa-bars"></i><i class="fa fa-arrow-circle-o-down"></i>
        <% end %>
      </div>
    </div>
  </div>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
  <div class=" col-md-4">
    <div class="text-center">
    </div>
  </div>
  <div class=" col-md-4">
    <div class="text-center">
      <%= link_to root_path, class: 'btn btn-info' do %>
          <i class="fa fa-home"></i><strong> Back to Home </strong>
      <% end %>
    </div>
  </div>
  <div class=" col-md-4">
    <div class="text-center">
    </div>
  </div>
</div>




<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Note</h4>
      </div>
      <div class="modal-body">
        These project were created with basic knowledge of programming or school projects.... These work doesn't reflect
        my current skills. Please feel free to visit advanced or intermediate projects by closing this tab. If you still
        want to continue please click the link below...
      </div>
      <div class="modal-footer">
        <%= link_to school_index_path, class: 'btn btn-success' do %>
            <strong>Basic School
              Projects </strong><i class="fa fa-bars"></i><i class="fa fa-arrow-circle-o-down"></i>
        <% end %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>

app/views/intermediated/index.html.erb
<div class="container">
  <h3 class="header text-muted text-center">
    <strong><i class="fa fa-github" aria-hidden="true"></i> Open Source Project</strong>
  </h3>

  <div class="row placeholders">
    <div class="col-md-12 placeholder">
      <div class="col-md-8 placeholder">
        <h4 class="header text-info">
          <strong><i class="fa fa-hand-o-right" aria-hidden="true"></i> Reaktor Summer Intern App Challenge
            2015
          </strong>
        </h4>
        <p>
          <h4>
            <small>URL shortening app which saves long url and generate a random id and attach with base
              url(https://dry-earth-7085.herokuapp.com/)
            </small>
          </h4>
        </p>
      </div>
      <div class="col-md-2 placeholder">
        <%= link_to '<strong>Demo app</strong><i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i>'.html_safe, 'https://dry-earth-7085.herokuapp.com/', class: 'btn btn-success', :target => '_blank' %>
      </div>
      <div class="col-md-2 placeholder">
        <%= link_to '<strong>Github</strong><i class="fa fa-github"></i>'.html_safe, 'https://github.com/surajneupane55/ReaktorUrlShorteningTask', class: 'btn btn-success', :target => '_blank' %>
      </div>
    </div>
    <div class="col-md-12 placeholder">
      <div class="col-md-8 placeholder">
      <h4 class="header text-info">
        <strong><i class="fa fa-hand-o-right" aria-hidden="true"></i> Learning to trade NASDAQ!
        </strong>
      </h4>
      <p>
      <h4>
        <small>LAMP stack app, let you create account and provide you with 10000 USD to buy and sale NASDAQ stock, you
          can follow your performance!
        </small>
        <small class="text-danger">This app will be upgraded to production level in advance projects</small><br><small class="text-warning">UserName:surajnew55<br>PassWord:44</small>

      </h4>
      </p>

    </div>
      <div class="col-md-2 placeholder">
        <%= link_to '<strong>Demo app</strong><i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i>'.html_safe, 'http://learningmarket.azurewebsites.net/', class: 'btn btn-success', :target => '_blank' %>
      </div>
      <div class="col-md-2 placeholder">
        <%= link_to '<strong>Github</strong><i class="fa fa-github"></i>'.html_safe, 'https://github.com/surajneupane55/Php-MyApp', class: 'btn btn-success', :target => '_blank' %>
      </div>
    </div>
  </div>
</div>





<br><br><br>
<br><br><br>

<div class="container">
  <div class="text-center">
    <%= link_to dashboard_index_path, class: 'btn btn-info' do %>
        <i class="fa fa-arrow-left" aria-hidden="true"></i><strong> Back to Dashboard </strong>
    <% end %>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
<%=render partial: 'footer'%>

</body>
</html>

app/views/school/index.html.erb
<div class="container">
  <div class="header clearfix test-muted">
    <h3 class="text-muted text-center"><strong><i class="fa fa-github"></i> My School Project</strong></h3></h3>
  </div>
  <div class="container">
    <div class="row placeholders">
      <div class="col-md-5 placeholder text-center well well-bg">
        <h4 class="header text-center"><strong>Lahjapaja Oy</strong></h4>
        <p>
        <h4>
          <small><strong>LogIn as costumer, employee and admin with different right. For example, costumer can only see
            the
            order while employee can CURD costumer info and admin can CURD employee and costumer both.
          </strong></small>
        </h4>
        </p>
        <p><h4><strong>#Bootstrap #JQuery #MVC 4 #C-Sharp #.Net #MSSQL #Azure deployment, #Github</strong></h4></p>
        <p>
        <h4>
          <small><strong>Flaws: frontend design breakdown , password lacks encryption not secured for production</strong></small>
        </h4>
        </p>
        <table class="table table-bordered ">
          <tbody>
          <tr>
            <td>Role</td>
            <td>Username</td>
            <td>Password</td>
          </tr>
          <tr>
            <td>admin, employee, customer</td>
            <td>Admin1, Emp1, Cust1</td>
            <td>1234</td>
          </tr>
          </tbody>
        </table>
        <div class="row placeholders">
          <div class="col-md-6">
            <%= link_to '<strong>Demo app</strong><i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i>'.html_safe, 'http://layaapaja.azurewebsites.net/', class: 'btn btn-success', :target => '_blank' %>
          </div>
          <div class="col-md-6">
            <%= link_to '<strong>Github</strong><i class="fa fa-github"></i>'.html_safe, 'https://github.com/surajneupane55/Mvc_Project', class: 'btn btn-success', :target => '_blank' %>
          </div>
        </div>
      </div>
      <div class="col-md-2 placeholder"></div>
      <div class="col-md-5 placeholder text-center well well-bg"> <h4 class="header text-center"><strong>My Profile</strong></h4>
        <p>
        <h3>
          <small><strong>First hands on Ruby on rails, simple profile application to get used to with Ruby on rails environment
          </strong></small>
        </h3>
        </p>
        <p><h4><strong>#Bootstrap #JQuery #Ruby #Rails #Heroku #Postgres #Github</strong></h4></p>
        <p>
        <h4>
          <small><strong>Flaws: need to improve app performance and UI design.......</strong></small>
        </h4>
        </p>
        <div class="row placeholders">
          <div class="col-md-6">
            <%= link_to '<strong>Demo app</strong><i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i>'.html_safe, 'http://afternoon-waters-5323.herokuapp.com', class: 'btn btn-success', :target => '_blank' %>
          </div>
          <div class="col-md-6">
            <%= link_to '<strong>Github</strong><i class="fa fa-github"></i>'.html_safe, 'https://github.com/surajneupane55/Profile', class: 'btn btn-success', :target => '_blank' %>
          </div>
        </div></div>
    </div>
    <div class="row placeholder">
      <div class="text-center">
        <%= link_to dashboard_index_path, class: 'btn btn-info' do %>
            <i class="fa fa-arrow-left" aria-hidden="true"></i><strong> Back to Dashboard </strong>
        <% end %>
      </div>
    </div>
  </div>
</div>


<!-- /.container -->

app/views/shared/_navigation.html.erb
    <h5 class="page-header text-center "><i class="fa fa-arrow-circle-down"></i><strong>Navigate</strong><i class="fa fa-link"></i></h5>
    <div class="row placeholders">
        <div class="row-xs-6 row-sm-4 placeholder" title="my profile">
            <img data-src="holder.js/50x50/auto/<%= @users ? 'lava' : 'vine' %>/text: " id="image" class="img-responsive" alt="200x200" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzBEOEZEQiIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjEwMCIgeT0iMTAwIiBzdHlsZT0iZmlsbDojZmZmO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjEzcHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MjAweDIwMDwvdGV4dD48L3N2Zz4=">
              <%=link_to '<i class="fa fa-suitcase" title="my profile"></i>'.html_safe, root_path(filter: 'profile')%>
        </div>
        <div class="row-xs-6 row-sm-4 placeholder" title="education">
            <img data-src="holder.js/50x50/auto/<%= @education ? 'lava' : 'vine' %>/text: " id="image" class="img-responsive" alt="200x200" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzBEOEZEQiIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjEwMCIgeT0iMTAwIiBzdHlsZT0iZmlsbDojZmZmO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjEzcHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MjAweDIwMDwvdGV4dD48L3N2Zz4=">
            <%=link_to '<i class="fa fa-graduation-cap" title="education"></i>'.html_safe,root_path(filter: 'education')%>
        </div>
        <div class="row-xs-6 row-sm-4 placeholder" title="software skills">
            <img data-src="holder.js/50x50/auto/<%= @projects ? 'lava' : 'vine' %>/text: " class="img-responsive" alt="200x200" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzBEOEZEQiIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjEwMCIgeT0iMTAwIiBzdHlsZT0iZmlsbDojZmZmO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjEzcHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MjAweDIwMDwvdGV4dD48L3N2Zz4=">

    <%=link_to '<i class="fa fa-git"  title="software skills"></i>'.html_safe, root_path(filter: 'git') %>
        </div>

        <div class="row-xs-6 row-sm-4 placeholder" title="my blog">
            <img  data-src="holder.js/50x50/auto/<%= @blogs ? 'lava' : 'vine' %>/text: " class="img-responsive" alt="200x200" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzBEOEZEQiIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjEwMCIgeT0iMTAwIiBzdHlsZT0iZmlsbDojZmZmO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjEzcHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MjAweDIwMDwvdGV4dD48L3N2Zz4=">
            <%=link_to'<i class="fa fa-pencil"  title="my blog"></i>'.html_safe, root_path(filter:'blog') %>
        </div>

        <div class="row-xs-6 row-sm-4 placeholder" title="IT consultant skills">
            <img data-src="holder.js/50x50/auto/<%=@businesses ? 'lava' : 'vine'%>/text: " class="img-responsive" alt="200x200" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzBEOEZEQiIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjEwMCIgeT0iMTAwIiBzdHlsZT0iZmlsbDojZmZmO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjEzcHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MjAweDIwMDwvdGV4dD48L3N2Zz4=">
            <%=link_to '<i class="fa fa-user"  title="IT consultant skills"></i>'.html_safe,root_path(filter:'business') %>
        </div>

        <div class="row-xs-6 row-sm-4 placeholder" title="dashboard">
            <img data-src="holder.js/50x50/auto/vine/text: " class="img-responsive" alt="200x200" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzBEOEZEQiIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjEwMCIgeT0iMTAwIiBzdHlsZT0iZmlsbDojZmZmO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjEzcHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MjAweDIwMDwvdGV4dD48L3N2Zz4=">
           <%= link_to '<i class="fa fa-tachometer"  title="dashboard"></i>'.html_safe, index_path %>
        </div>
    </div>

app/views/user/index.html.erb
<div class="container">
    <h3 class=" header text-muted text-center">
        <i class="fa fa-university"></i>
        <strong>Minun Profiili</strong>
    </h3>

   <div class="container">
       <div class="row placeholders">
        <div class="col-xs-3 col-md-3 placeholder">
        </div>
        <div class="col-xs-12 col-md-6 placeholder">
            <div class="table table-responsive">
                <table class="table table-striped ">
                    <tbody>
                    <tr>
                        <th>Nimi</th>
                        <td>Suraj Neupane</td>
                    </tr>
                    <tr>
                        <th>Ikä</th>
                        <td>27</td>
                    </tr>
                    <tr>
                        <th>Koulutus</th>
                        <td>Haaga-Helia (BITe, Valmistuminen 2015/2016)</td>
                    </tr>
                    <tr>
                        <th>Kansalaisuus</th>
                        <td>Suomi/Nepali</td>
                    </tr>
                    </tbody>
                </table>
                <table class="table table-striped ">
                    <tbody>
                        <th class="text-center">Kielitaidot</th>

                        <tr>
                            <td><strong>Kieli</strong></td>
                            <td><strong>Taso</strong></td>
                            <td><strong>Järjestelijä</strong></td>
                        </tr>
                        <tr>
                            <td><strong>Suomi</strong></td>
                            <td>Keski-taso (YKI taso 3 tai 4, Tammikuu 2016)</td>
                            <td>OpetusHallitus</td>
                        </tr>
                        <tr>
                            <td><strong>Englanti</strong></td>
                            <td>Yli-taso (IELTS 6.5 piste, 2009)</td>
                            <td>British Council</td>
                        </tr>
                        <tr>
                            <td><strong>Hindi</strong></td>
                            <td>Yli-taso</td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td><strong>Nepali</strong></td>
                            <td>Äidinkieli</td>
                            <td>-</td>
                        </tr>
                    </tbody>
                </table>
                    <div class="text-center">
                        <%= link_to dashboard_index_path,  class: 'btn btn-success', 'id' => 'displayModal'  do %>
                        <strong>Dashboard </strong><i class="fa fa-bars"></i><i class="fa fa-arrow-circle-o-right"></i>
                    <%end%>
                    </div>
            </div>
        </div>
        <div class="col-xs-3 col-md-3 placeholder">
        </div>
        </div>
   </div>

</div>